export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
//Auth
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';
// Account
export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO';
export const CHANGE_ACCOUNT_PASSWORD = 'CHANGE_ACCOUNT_PASSWORD';
export const SET_CURRENT_ACCOUNT_PLAN = 'SET_CURRENT_ACCOUNT_PLAN';